---
name: 'Yamllint GitHub Actions'
on:
  - pull_request
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Yamllint branch-release'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'branch-release'

      - name: 'Yamllint merge-release'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'merge-release'

      - name: 'Yamllint workflows'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/workflows'